JnJ/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('managing.urls')),
    path('formtesting/', include('formtesting.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls' # the namespace to call from any template
urlpatterns = [
    # ex: /polls/
    # the name here is to call this path from a django template with the url command
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    path('<int:pk>', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    # also int will helps django to know what patterns should match this part of the URL
    # path('<int:question_id>/results/', views.results, name='results'),
    path('<int:pk>/results/', views.ResultView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # testing with layout
    # path('layout', views.layout, name='layout'),
    # testing with searching form
    # path('search', views, name='search'),
    path('enter-name', views.enter_name, name='enter-name'),
    path('your-name', views.your_name, name='your-name'),

]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)  # this means that each Choice is related to a single Question
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    @admin.display(boolean=True, ordering='pub_date', description='Published recently?')
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.http import Http404

# shortcut
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice
from django.contrib.auth.models import User


# from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# My index view
def index_old(request):
    return_content = """
    <h1>Hello world</h1>
    <a href="https://docs.djangoproject.com/en/3.2/intro/tutorial03/" >Writing your first Django app, part 3</a>
    {list_content}
    """

    latest_question_list = Question.objects.order_by('pub_date')[:5]

    list_in_display = "".join(["<p>" + q.question_text + "</p>" for q in latest_question_list])

    return HttpResponse(return_content.replace("{list_content}", list_in_display))


# new views function -------------
def index_old2(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, "polls/index.html", context)


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


# Generic Views ----- This is the final code
class IndexView(LoginRequiredMixin,generic.ListView):
# class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    login_url = '/accounts/login/?next=/polls'

    def get_queryset(self):
        # return Question.objects.order_by('-pub_date')[:5]
        # return the last five published questions that is smaller or equal to now
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:6]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, "polls/detail.html", {
            'question': question,
            'error_message': "You didn't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question_id,)))


# def layout2(request):
#     template = loader.get_template('polls/layout.html')
#     return HttpResponse(template.render(request=request))


# def search(request, question_keyword):
#     questions = Question.objects.filter(question_text__in=question_keyword)
#     return render(request, 'polls/layout.html')

# playing with forms
def enter_name(request):
    """
    direct to the 'enter-name' site
    :param request:
    :return:
    """
    return render(request, 'polls/enter-name.html')


def your_name(request):
    try:
        context = {
            'the_name': request.POST['your_name']
        }
    except:
        context = {}

    return render(request, 'polls/your-name.html', context)

templates/polls/detail.html
{% extends 'polls/layout.html' %}

{% block content %}
    <h1 class="display-4">{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            {% for choice in question.choice_set.all %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <div class="input-group-text">
                        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    </div>
                </div>
            <label class="form-control" for="choice{{ forloop.counter }}" >{{ choice.choice_text }}</label><br>
            </div>


        {% endfor %}
        </div>

    <input class="btn btn-primary" type="submit" value="vote">

    </form>

{% endblock %}

templates/polls/enter-name.html
{% extends 'polls/layout.html' %}
{% block content %}
    <form action="{% url 'polls:your-name' %}" method="post">
        {% csrf_token %}
        <label for="your_name">Your name: </label>
{#        <input id="your_name" type="text" name="your_name" value="{{ current_name }}">#}
        <input id="your_name" type="text" name="your_name" >
        <input type="submit" value="OK">
    </form>
{% endblock %}

templates/polls/index.html
{% extends 'polls/layout.html' %}

{% block content %}
    <h1 class="card-header"><a
            href="https://docs.djangoproject.com/en/3.2/intro/tutorial07/">
        Customize the admin look and feel
    </a></h1>

    <h1><a href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication#logout_template">
        Logout Template</a></h1>

    <br>

    {% if latest_question_list %}
        <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Question</th>
                <th scope="col">Published Date</th>

            </tr>
            </thead>
            <tbody>

            {% for q in latest_question_list %}
                <tr>
                    <td scope="row"> {{ forloop.counter }}</td>
                    <td><a href="{% url 'polls:detail' q.id %}">{{ q.question_text }}</a></td>
                    <td>{{ q.pub_date }}</td>
                </tr>
            {% endfor %}


            </tbody>
        </table>

    {% else %}
        <h1 class="bg-info">No polls are available.</h1>
    {% endif %}

{% endblock %}

templates/polls/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Django App</title>

    <link rel="stylesheet" href="{% static 'polls/lib/bootstrap/dist/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'polls/css/site.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Yellowtail&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet">

</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-navbar border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" href="/polls/">光アルファクス</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="">API Call</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="/polls/enter-name">Enter Name</a>
                    </li>
                </ul>

                <div class="text-white">

                    {% if user.is_authenticated %}
                        <p>Hello, {{ user.get_username }} | <a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></p>
                    {% else %}
                        <p><a href="{% url 'login' %}?next={{ request.path }}">Login</a> </p>
                    {% endif %}


                </div>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        {% block content %}
        {% endblock %}
    </main>
</div>

<footer class="border-top footer text-white bg-footer">
    <div class="container">
        &copy; 2021 - Django App - <a href="">Privacy</a>
    </div>
</footer>

<script src="{% static 'polls/lib/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'polls/lib/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'polls/js/site.js' %}"></script>

</body>
</html>

templates/polls/results.html
{% extends 'polls/layout.html' %}

{% block content %}

    <h1 class="display-4">{{ question.question_text }}</h1>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Choices</th>
            <th scope="col">Vote Count</th>

        </tr>
        </thead>
        <tbody>

        {% for choice in question.choice_set.all %}
            {#                <li><a href="/pollapp/{{ q.id }}">{{ q.question_text }}</a></li>#}
            <tr>
                <th scope="row"> {{ forloop.counter }}</th>
                <td>{{ choice.choice_text }}</td>
                <td>{{ choice.votes }} vote{{ choice.votes|pluralize }}</td>
            </tr>
        {% endfor %}


        </tbody>
    </table>


    <a class="btn btn-secondary" href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}

templates/polls/search.html
{% extends 'polls/layout.html' %}

{% block content %}

    <form action="" method="post">

    </form>

    <br>

    {% if latest_question_list %}
        <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Question</th>
                <th scope="col">Published Date</th>

            </tr>
            </thead>
            <tbody>

            {% for q in latest_question_list %}
                <tr>
                    <th scope="row"> {{ forloop.counter }}</th>
                    <td><a href="{% url 'polls:detail' q.id %}">{{ q.question_text }}</a></td>
                    <td>{{ q.pub_date }}</td>
                </tr>
            {% endfor %}


            </tbody>
        </table>

    {% else %}
        <h1 class="bg-info">No polls are available.</h1>
    {% endif %}
{% endblock %}

templates/polls/your-name.html
{% extends 'polls/layout.html' %}
{% block content %}
    {% if the_name %}
        <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Item</th>
                <th scope="col">Value</th>


            </tr>
            </thead>
            <tbody>
                <td scope="row">Your Name</td>
                <td>{{ the_name }}</td>

            </tbody>
        </table>
    {% else %}
        <h1 class="alert-warning">There were no name entered!</h1>
    {% endif %}
{% endblock %}