JnJ/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('managing.urls')),
    path('formtesting/', include('formtesting.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

managing/urls.py
from django.urls import path

from . import views

app_name = 'managing' # K (kakkoi-kouritsu-kantan) ERP

urlpatterns = [
    path('', views.index_render, name='index'),
    path('about/', views.about, name='about'),
    path('comp/', views.comp_sel, name='comp_sel'),
    path('compselected/', views.comp_selected, name='comp_selected'),
    path('calendar/', views.calendar,name='calendar'),
]

managing/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin


# Create your models here.
class Company(models.Model):
    company_code = models.IntegerField()
    company_name = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return str(self.company_code) + ', ' + self.company_name

    @admin.display(boolean=True, ordering='pub_date', description='Published recently?')
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

managing/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from .models import Company

import datetime

# Create your views here.
def index_render(request):
    return login_and_comp_selected(request, 'managing/index.html')


def about(request):
    return login_and_comp_selected(request, template_name='managing/about.html')


def comp_sel(request):
    if request.user.is_authenticated:
        all_company = Company.objects.all()
        context = {'comp_list': all_company}
        return render(request, 'managing/comp_sel.html', context)
    else:
        return render(request, 'registration/login.html')


def comp_selected(request):
    if request.user.is_authenticated:
        selected_comp = Company.objects.get(company_code=request.POST['comp'])
        request.session['sel_comp'] = selected_comp.company_name
        # return render(request, 'managing/index.html')
        return HttpResponseRedirect(reverse('managing:index'))
    else:
        return render(request, 'registration/login.html')



def calendar(request):
    if request.user.is_authenticated:

        """
        I want to get the whole date and weekday list in a dictionary manner
        [{1: 'Mon'}, {2: 'Tue'}...]
        """
        today = datetime.datetime.now()
        num_days = days_in_month(today.year, today.month)

        this_month = []

        for i in range(1, num_days + 1):
            this_month += [{'day': i , 'weekday': get_weekday(today.weekday(), today.day - i)}]

        context = {'this_month': this_month}
        return render(request, 'managing/calendar.html', context) # ⭐️Need to add this template to templates/managing
    else:
        return render(request, 'registration/login.html')


def login_and_comp_selected(request, template_name):
    if request.user.is_authenticated and 'sel_comp' in request.session:
        return render(request, template_name)
    elif 'sel_comp' in request.session == False:
        all_company = Company.objects.all()
        context = {'comp_list': all_company}
        return render(request, 'managing/comp_sel.html', context)
    else:
        return render(request, 'registration/login.html')


# ----------------
# -1 is a placeholder for indexing purposes.
_DAYS_IN_MONTH = [-1, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
_WEEKDAY = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']


def is_leap(year):
    return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)


def days_in_month(year, month):
    assert 1 <= month <= 12, month
    if is_leap(year) and month == 2:
        return 29
    return _DAYS_IN_MONTH[month]


def get_weekday(base_weekday, days_diff):
    return _WEEKDAY[base_weekday + (int(days_diff/ 7) * 7 - days_diff)] # this one works
    #return _WEEKDAY[(days_diff - base_weekday) % 7] # still working on it


def test_mycode():
    today = datetime.datetime.now()
    num_days = days_in_month(today.year, today.month)

    this_month = []

    for i in range(1, num_days + 1):
        this_month += [{'day': i , 'weekday': get_weekday(today.weekday(), today.day - i)}]
        print(this_month)

    #print(this_month)

templates/managing/about.html
{% extends 'managing/_layout.html' %}

{% block content %}

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">K-ERPとは</h1>
    <div class="card shadow mb-1">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">定義</h6>
        </div>
        <div class="card-body">
            <p><code>企業</code> のため、そして<code>ユーザー</code>のための初の<code>K</code>が含まれている<code>ERPシステム</code>でございます。
                <br>
                これからERPは恐ろしいものではありません。</p>
            <a href="#" class="btn btn-primary btn-icon-split">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-flag"></i>
                                        </span>
                <span class="text">1K - 簡単</span>
            </a>
            <div class="my-2"></div>
            <a href="#" class="btn btn-success btn-icon-split">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-check"></i>
                                        </span>
                <span class="text">2K - 効率</span>
            </a>
            <div class="my-2"></div>
            <a href="#" class="btn btn-warning btn-icon-split">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-arrow-right"></i>
                                        </span>
                <span class="text">3K - 確実</span>
            </a>
            <div class="my-2"></div>
            <a href="#" class="btn btn-info btn-icon-split">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-info-circle"></i>
                                        </span>
                <span class="text">4K - カスタマイズ</span>
            </a>


        </div>
    </div>


{% endblock %}

templates/managing/calendar.html
{% extends 'managing/_layout.html' %}

{% block content %}

    {% if 'sel_comp' in request.session %}
        <h1>{{ request.session.sel_comp }}のデータへようこそ！</h1>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable">
                    <thead>
                    <tr>
                        <th style="text-align:left !important;background:#FFD !important;">
                            <span style="display:none;">Schedule in </span>October 2021
                        </th>
                        {% for each_day in this_month %}
                            <th>{{ each_day.day }}</th>
                        {% endfor %}

                    </tr>
                    <tr class="weekdays">
                        <td>Weekday</td>
                        {% for each_day in this_month %}
                            <td>{{ each_day.weekday }}</td>
                        {% endfor %}

                    </tr>
                    <tr>
                        <td><a href="/calendar">Jack Franklin</a></td>
                        {% for each_day in this_month %}
                            <td style="text-align: center;">
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#assignModal">

                                    ○
                                </a>
                            </td>
                        {% endfor %}
                    </tr>
                    <tr>
                        <td><a href="/calendar">Jake Nguyen</a></td>
                        {% for each_day in this_month %}
                            <td style="text-align: center;">
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#assignModal">

                                    ○
                                </a>
                            </td>
                        {% endfor %}
                    </tr>

                    </thead>
                </table>
            </div>
        </div>


        <!-- Assign Modal-->
        <div class="modal fade" id="assignModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        {#                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>#}
                        <h5 class="modal-title" id="exampleModalLabel">Booking</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    {#                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>#}
                    <div class="modal-body">
                        <div>
                            <label>名前</label>
                            <div>name_variable</div>
                        </div>
                        <div>
                            <label>時間</label>
                            <div>time_variable</div>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">キャンセル</button>
                        {#                    <a class="btn btn-primary" href="{% url 'logout' %}?next={{ request.path }}">Logout</a>#}
                        <button class="btn btn-primary" type="button" data-dismiss="modal">設定</button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

templates/managing/comp_sel.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>JnJ ログイン</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'managing/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'managing/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-company-select"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">会社を選択してください:</h1>
                                    </div>



    <form action="{% url 'managing:comp_selected' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            {% for comp in comp_list %}
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                       <div class="input-group-text">
                         <input type="radio" name="comp" id="comp{{ forloop.counter }}" value="{{ comp.company_code }}">
                       </div>
                    </div>
                     <label class="form-control" for="comp{{ forloop.counter }}" >{{ comp.company_code }} : {{ comp.company_name }}</label><br>
                 </div>


            {% endfor %}
        </div>
        <input class="btn btn-primary" type="submit" value="会社選択">
    </form>
                                    <hr>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'managing/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'managing/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'managing/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'managing/js/sb-admin-2.min.js' %}"></script>

</body>

</html>

templates/managing/index.html
{% extends 'managing/_layout.html' %}

{% block content %}


    {% if 'sel_comp' in request.session %}
        <h1>{{ request.session.sel_comp }}のデータへようこそ！</h1>

        <h2>Please select <a href="calendar/"><strong>カレンダー機能</strong></a> to check the calendar feature</h2>

    {% endif %}

{% endblock %}